name: Build and deploy on push to novaprime/main

on:
  push:
    branches: [novaprime/main]

jobs:
  create-image-tag:
    name: "Creating Image Tag"
    uses: ./.github/workflows/novaprime-workflow-image-tag.yml

  build-image:
    name: "Build and Push Container Image"
    needs:
      - create-image-tag
    secrets: inherit
    uses: ./.github/workflows/novaprime-workflow-build-images.yml
    with:
      image_tag: ${{ needs.create-image-tag.outputs.image_tag }}
      push_images: true